// ==UserScript==
// @name         4chan_trial
// @namespace    https://4chan.org/
// @version      2024-08-29
// @description  Copy the image urls from the page.
// @author       You
// @match        https://boards.4chan.org/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==


// Gets the first post in the thread
var op = document.getElementsByClassName('op')[0];
// Node list for every post info (The part where it says the time and shit in a post)
var posts = document.getElementsByClassName('postInfo');
// Checkbox created by the script
var checkbox;
// It's the "Download: " text you see before every checkbox generated by the script
var phrase;

function get_urls(evt){
    evt.preventDefault();
    var imageList = [];
    var imgParentList = document.getElementsByClassName("fileThumb");
    if(null != imgParentList && imgParentList.length > 0){
        for(let i = 0; i < imgParentList.length ; i++){
            let childNodeData = imgParentList[i].href;
            //console.log(childNodeData);
            imageList.push(childNodeData);
        }
    }

    //navigator.clipboard.writeText(imageList);
    for(var i = 0; i <= 1 //imageList.length
        ; i++){
        var img_split = imageList[i].split('/');
        var img_name = img_split[img_split.length-1];
        //downloadImage_v1(imageList[i],img_name);
        console.log(imageList[i]);
    }
    navigator.clipboard.writeText(imageList);
}
// Creates buttons
function create_button(button_text, click_function) {
    // Creates a HTML element (In this case a <button> element)
    var name = document.createElement('BUTTON');
    // Creates the text for the button
    var name_text = document.createTextNode(button_text);

    // Adds the text to the button
    name.appendChild(name_text);

    // Makes buttons do something when they're clicked
    name.addEventListener('click', click_function, false);

    // Adds the button to OP's post
    op.appendChild(name);
}

function downloadAllImages(evt){
    evt.preventDefault();
    var currThreadSplit = window.location.href.split('/');
    var currThreadNumber = currThreadSplit[currThreadSplit.length - 1];
    var imgParentList = document.getElementsByClassName("fileThumb");
    if(null != imgParentList && imgParentList.length > 0){
    for(let i = 0; i < imgParentList.length ; i++){
        let childNodeData = imgParentList[i].href;
	fetch(childNodeData)
		// check to make sure you didn't have an unexpected failure (may need to check other things here depending on use case / backend)
		.then(resp => resp.status === 200 ? resp.blob() : Promise.reject('something went wrong'))
		.then(blob => {
		const url = window.URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.style.display = 'none';
		a.href = url;
		// the filename you want
        var img_split = childNodeData.split('/');
        //modify this to select folder and all
        var img_name = currThreadNumber + "_" + img_split[img_split.length-1];
		a.download = img_name;
		document.body.appendChild(a);
		a.click();
		window.URL.revokeObjectURL(url);
		console.log(img_name + ' has been downloaded!');
	})
  .catch(() => alert('oh no!'));
    }
}
}

// Fun-fact: send_data is correct and send_data() is wrong. Don't ask me why
create_button('Download images', get_urls);
create_button('Download All images', downloadAllImages);
